[versions]
androidGradlePlugin = "8.13.2"
supportLibrary = "26.1.0"
butterknife = "8.8.1"
junit4 = "4.12"
junit = "4.13.2"
androidxAnnotation = "1.6.0"
timelineView = "1.0.5"

[libraries]
supportAppcompat = { module = "com.android.support:appcompat-v7", version.ref = "supportLibrary" }
supportDesign = { module = "com.android.support:design", version.ref = "supportLibrary" }
supportCardview = { module = "com.android.support:cardview-v7", version.ref = "supportLibrary" }
butterknife = { module = "com.jakewharton:butterknife", version.ref = "butterknife" }
butterknifeCompiler = { module = "com.jakewharton:butterknife-compiler", version.ref = "butterknife" }
junit4 = { module = "junit:junit", version.ref = "junit4" }
junit = { module = "junit:junit", version.ref = "junit" }
androidxAnnotation = { module = "androidx.annotation:annotation", version.ref = "androidxAnnotation" }
timelineView = { module = "com.github.vipulasri:timelineview", version.ref = "timelineView" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
